// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFTNPrXSy6TZch3KE0iK7PzRgfV2oqHeU',
    appId: '1:896672687821:web:e0986978200fdb5c02eb84',
    messagingSenderId: '896672687821',
    projectId: 'flutterapp-75762',
    authDomain: 'flutterapp-75762.firebaseapp.com',
    storageBucket: 'flutterapp-75762.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCsU9ojIf_PMiH7I0wMcmi0qgtcf7nSMI',
    appId: '1:896672687821:android:07a41a244ae86f4b02eb84',
    messagingSenderId: '896672687821',
    projectId: 'flutterapp-75762',
    storageBucket: 'flutterapp-75762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqtVcFq9vPPFTUb9OZYrAV-3bK0l2gQMY',
    appId: '1:896672687821:ios:8f471621b5ad39e102eb84',
    messagingSenderId: '896672687821',
    projectId: 'flutterapp-75762',
    storageBucket: 'flutterapp-75762.firebasestorage.app',
    iosBundleId: 'com.example.moblieKakkak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqtVcFq9vPPFTUb9OZYrAV-3bK0l2gQMY',
    appId: '1:896672687821:ios:8f471621b5ad39e102eb84',
    messagingSenderId: '896672687821',
    projectId: 'flutterapp-75762',
    storageBucket: 'flutterapp-75762.firebasestorage.app',
    iosBundleId: 'com.example.moblieKakkak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFTNPrXSy6TZch3KE0iK7PzRgfV2oqHeU',
    appId: '1:896672687821:web:e587af31fad3ca6502eb84',
    messagingSenderId: '896672687821',
    projectId: 'flutterapp-75762',
    authDomain: 'flutterapp-75762.firebaseapp.com',
    storageBucket: 'flutterapp-75762.firebasestorage.app',
  );
}
